package cn.lunadeer.dominion.uis.chest;

public enum MenuId {
    MAIN, DOMINION_LIST, ALL_DOMINIONS, CHILD_LIST, DASHBOARD,
    AREA, PERMISSIONS, PEOPLE, APPEARANCE, OWNERSHIP, RESIZE,
    ENV_FLAGS, GUEST_FLAGS, MEMBER_LIST, MEMBER_DETAIL, MEMBER_FLAGS,
    GROUP_LIST, GROUP_DETAIL, GROUP_FLAGS, GROUP_MEMBER_PICKER,
    PLAYER_PICKER, TRANSFER_PICKER, TEMPLATE_LIST, TEMPLATE_DETAIL,
    TEMPLATE_FLAGS, TEMPLATE_PICKER, TITLE_LIST, COPY_SOURCE, COPY_TYPE,
    CONFIRM
}
